package com.example.user;

import com.example.user.adapter.db.UserRepositoryAdapter;
import com.example.user.model.PagedUsers;
import com.example.user.model.User;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.transaction.annotation.Transactional;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Integration test that replaces H2 with a real PostgreSQL container via Testcontainers.
 *
 * <p>{@link ServiceConnection} (Spring Boot 3.1+) overrides the {@code spring.datasource.*}
 * properties at runtime, pointing them at the ephemeral PostgreSQL container.
 * Flyway then runs the production SQL migrations ({@code db/migration/V*.sql}) against
 * the real PostgreSQL dialect — catching dialect mismatches that H2-compatible mode misses.
 *
 * <p>{@code webEnvironment = NONE} keeps the test fast by not starting an HTTP server.
 *
 * <h2>What is tested</h2>
 * <ul>
 *   <li>Flyway migration executes successfully against PostgreSQL</li>
 *   <li>Save / find-by-id round-trip</li>
 *   <li>Case-insensitive e-mail uniqueness check</li>
 *   <li>Paginated find-all</li>
 *   <li>Unpaged find-all</li>
 *   <li>Full-field update</li>
 *   <li>Delete by ID</li>
 * </ul>
 */
@SpringBootTest(
        webEnvironment = SpringBootTest.WebEnvironment.NONE,
        properties = {
                "spring.flyway.enabled=true",
                "spring.flyway.baseline-on-migrate=true",
                // Rely on Flyway to create the schema (not Hibernate auto-ddl)
                "spring.jpa.hibernate.ddl-auto=validate",
                // Security auto-configurations require a servlet context to build
                // HttpSecurity — exclude them for this DB-only integration test.
                "spring.autoconfigure.exclude=" +
                        "org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration," +
                        "org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration," +
                        "org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration"
        }
)
@Testcontainers
@Transactional  // each test method runs in a transaction that is rolled back afterward
class UserRepositoryContainerTest {

    /** PostgreSQL 17 — same major version used in docker-compose.yml. */
    @Container
    @ServiceConnection
    static final PostgreSQLContainer<?> postgres =
            new PostgreSQLContainer<>("postgres:17-alpine");

    @Autowired
    private UserRepositoryAdapter adapter;

    // ─── save / find ──────────────────────────────────────────────────────────

    @Test
    void saveAndFindRoundTripWithRealPostgres() {
        User saved = adapter.save(User.createBuyer(null, "bob@testcontainer.test", "Bob"));

        assertNotNull(saved.id(), "ID must be generated by PostgreSQL IDENTITY column");
        User retrieved = adapter.findById(saved.id()).orElseThrow();
        assertEquals("bob@testcontainer.test", retrieved.email());
        assertEquals("Bob", retrieved.displayName());
    }

    // ─── email uniqueness ─────────────────────────────────────────────────────

    @Test
    void detectsExistingEmailCaseInsensitively() {
        adapter.save(User.createBuyer(null, "sam@testcontainer.test", "Sam"));

        assertTrue(adapter.existsByEmail("SAM@TESTCONTAINER.TEST"),
                "existsByEmail must be case-insensitive");
        assertTrue(adapter.existsByEmail("sam@testcontainer.test"));
    }

    // ─── paginated find-all ───────────────────────────────────────────────────

    @Test
    void findAllPagedReturnsCorrectWindow() {
        adapter.save(User.createBuyer(null, "pg-a@testcontainer.test", "A"));
        adapter.save(User.createBuyer(null, "pg-b@testcontainer.test", "B"));
        adapter.save(User.createBuyer(null, "pg-c@testcontainer.test", "C"));

        PagedUsers page = adapter.findAll(0, 2);

        assertEquals(2, page.content().size(), "First page must contain 2 entries");
        assertTrue(page.totalElements() >= 3, "Total count must reflect all inserted rows");
        assertTrue(page.totalPages() >= 2, "At least 2 pages needed for 3+ rows with page size 2");
        assertEquals(0, page.pageNumber());
    }

    // ─── unpaged find-all ─────────────────────────────────────────────────────

    @Test
    void findAllUnpagedReturnsEveryRow() {
        adapter.save(User.createBuyer(null, "pg-x@testcontainer.test", "X"));
        adapter.save(User.createBuyer(null, "pg-y@testcontainer.test", "Y"));
        adapter.save(User.createBuyer(null, "pg-z@testcontainer.test", "Z"));

        List<User> all = adapter.findAll();

        assertTrue(all.size() >= 3, "All rows must be returned when unpaged");
    }

    // ─── update ───────────────────────────────────────────────────────────────

    @Test
    void updatePersistsFieldChanges() {
        User saved = adapter.save(User.createBuyer(null, "before@testcontainer.test", "Before"));

        User updated = adapter.update(User.createBuyer(saved.id(), "after@testcontainer.test", "After"));

        assertEquals("after@testcontainer.test", updated.email());
        assertEquals("After", updated.displayName());
        assertEquals(saved.id(), updated.id());

        // Re-read to confirm persistence
        User reloaded = adapter.findById(saved.id()).orElseThrow();
        assertEquals("after@testcontainer.test", reloaded.email());
        assertEquals("After", reloaded.displayName());
    }

    // ─── delete ───────────────────────────────────────────────────────────────

    @Test
    void deleteRemovesRow() {
        User saved = adapter.save(User.createBuyer(null, "todelete@testcontainer.test", "ToDelete"));

        adapter.deleteById(saved.id());

        assertTrue(adapter.findById(saved.id()).isEmpty(),
                "Row must be absent after deleteById");
    }
}
